title: Tanushree Dutta # your name (or website title) here
logo: "/images/LI_dp.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Assistant Manager 
  Corporate Planning and Management Services 
  Airport Authority Of India.
  <br><br>
  <a href="https://www.linkedin.com/in/tanushree-dutta-632b55a9/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
